version: '3.5'

services:
  db:
    # image: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=conceitos_nest
    container_name: conceitos_nest_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conceitos_nest
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      # ensures that anything generated in /app/db/migrations inside the container is mirrored to
      # ./db/migrations in your local directory.
      - ./db/migrations:/app/db/migrations
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: conceitos_nest_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - postgres-network

volumes:
  pgdata:

networks:
  postgres-network:
    driver: bridge
